{
 "title": "qket",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "백엔드 cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"qket-release\", container=\"qket-backend\"}[5m])) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "프론트 cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"qket-release\", container=\"qket-frontend\"}[5m])) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "평균 응답시간 (ms, 엔드포인트별)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum{namespace=\"qket-release\"}[5m])) / sum by (uri) (rate(http_server_requests_seconds_count{namespace=\"qket-release\"}[5m])) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "요청 수 (초당, 엔드포인트별)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{namespace=\"qket-release\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}