apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
    - secretKey: email-username
      remoteRef:
        key: {{ .Values.secretArn | quote }}
        property: email-username
    - secretKey: email-password
      remoteRef:
        key: {{ .Values.secretArn | quote }}
        property: email-password
